---
- remote_user: ubuntu
  become: yes
  become_method: sudo

  tasks:
  - name: Install Apache
    apt:
      name: apache2
      update_cache: yes
  - name: Copying the demo file
    template: src=index.html dest=/var/www/html
              owner=www-data group=www-data mode=0644
